---
# /app/caib/radarcov/
external:
  application:
    properties: "/app/caib/radarcov/application.properties"
# App specific
dp3t:
  ibcovid:
    codegen:
      clients:
        auth: "http://localhost:10103/v1"
      # Expiration duration in hours
      expiration-duration: 24
      tasks:
        url: "/v1/admin/downloaded-access-code"
        url-generate-codes: "/v1/admin/downloaded-access-code/generate-codes"
        url-generate-codes-test: "/v1/admin/downloaded-access-code/generate-codes/test"
        url-send-sms: "/v1/admin/downloaded-access-code/generate-codes"

application:
  radarcovid:
    sms-url: "http://bitsms.fundaciobit.org/bitsms/MensajeEnviar?remitente=APPCOVID&numero={number}&texto={texto}&idCampanya=APPCOVID"
    sms-text: "Su código para Radar Covid es %s."
    sms-user: "jorge.sanchezferreiro@plexus.es"
    sms-password: "Tecnocrata-666"
#
#jwt:
#  PRIVATE_KEY_FILE: "classpath://generated_private_base64.pem"
#  ALGORITHM: "EC"
#  CCAA_SUBJECT: "04"
#  CCAA_ISSUER: "ISSUER"
#  TOKEN_MINS_EXPIRES: 15

spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.Oracle10gDialect
  # Database
  datasource:
    jndi-name: "java:/es.caib.radarcov.db"

# Logging
logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.SQL.type.descriptor.sql: TRACE
    es.caib.dp3t.ibcovid: DEBUG
