---
# App specific
dp3t:
  ibcovid:
    codegen:
      clients:
        auth: "http://localhost:10103/v1"
      private-key: "classpath:/cert/private.key"
      public-key: "classpath:/cert/public.key"
      # Expiration duration in hours
      expiration-duration: 24
      tasks:
        delete-exposed-access-codes:
          cron: "0 */30 * ? * *"

spring:
  main:
    banner-mode: off
  profiles:
    active: @activeSpringProfiles@
  jpa:
    # Hibernate
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    open-in-view: false

  # Database migration
  flyway:
    enabled: @enableDBMigration@
    baseline-on-migrate: true
    table: "flyway_history_codegen"
    locations: "classpath:db/migration/@databaseDialect@"

logging:
  config: classpath:log4j2-@activeEnvironment@.yml

jwt:
    PRIVATE_KEY_FILE: "classpath://generated_private_base64.pem"
    ALGORITHM: "EC"
    CCAA_SUBJECT: "04"
    CCAA_ISSUER: "ISSUER"
    TOKEN_MINS_EXPIRES: 15

application:
  radarcovid:
    size: 500
    url: "https://ddu362ufohvxt.cloudfront.net/verification/generate?n={number}"
    publicKey: "LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlHYk1CQUdCeXFHU000OUFnRUdCU3VCQkFBakE0R0dBQVFCU1l5cXZSQUFZVGM4dmNjblc3dDNaZE9QRkpsNAprOFFNTHBkZFhDakhRWEY1MEJDL2tMb2VWaTV3b1h4enZDRUdiVEo3RGVzY3ZRS1FGQXVaZkNmNDBnVUF4WW1rClZFeFl5Z3hSQVVBRW55Nk9iY08raTFwdnQyaWxMRlJwblV0WUxJS0xDdEZkWFpLeWFoak9RWnVBSU9aTTZKSHAKUksrUWR1OGhHMUE0NUdQMC9sST0KLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0t"
    sms-url: "http://bitsms.fundaciobit.org/bitsms/MensajeEnviar?remitente=APPCOVID&numero={number}&texto={texto}}&idCampanya=APPCOVID"
    sms-text: "Mensaje de prueba con @ desde BITSMS-PLEXUS."



cron:
  generate:
    frecuency: "0/30 * * * * ?"
